### ISSUE TITLE
Rename CONTRIBUTING.md to something else

### ISSUE THREAD

**Issue by metacosm** [snowdrop/snowdrop-cloud-devex#59]
since it's not about contributions to the project at all and this file is handled specifically by github (i.e. changing it as implications, though ones we can ignore).

**Comment by geoand** [comment]
README_DEV maybe?

**Comment by geoand** [comment]
Or `DEVELOPERS`?

**Comment by cmoulliard** [comment]
of for `DEVELOPERS`
